### ISSUE TITLE
When I try to open https://github.com/adafruit/Adafruit-PowerBoost-500-Basic-PCB sch file with Eagle 7.6, I get an error on line 6, column 56 that this is not an Eagle file.  What should I try next?

### ISSUE THREAD

**Issue by txpostman** [adafruit/Adafruit-PowerBoost-500-Basic-PCB#1]

**Comment by ladyada** [comment]
try eagle 6? the file is not bad, you'll need to figure out what you did wrong :)

**Comment by txpostman** [comment]
> No description provided.

d it out.  I tried to download from the screen where the files are visible but I needed to download the zip file.  SCH and BRD files are not valid unless the zip or clone is used.  Thanks
